[package]
name = "mytheme"
version = "0.0.1"
description = ""
license = "MIT"
default-run = "mt"

[dependencies]
clap = { version = "4.3.11", features = ["derive"] }
crossbeam = "0.8.2"
prql-compiler = "0.8.1"
rayon = "1.7.0"
rusqlite = { version = "0.29.0", features = ["bundled"] }
serde = { version = "1.0.167", features = ["derive"] }
serde_json = "1.0.100"

[lib]
name = "mt"
path = "src/lib/main.rs"

[[bin]]
name = "mt"
path = "src/bin/mt.rs"

[[bin]]
name = "mytheme"
path = "src/bin/mytheme.rs"
