[package]
name = "mytheme"
version = "0.0.1"
description = ""
license = "MIT"
default-run = "mt"

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
crossbeam = "0.8.2"
prql-compiler = "0.5.2"
rayon = "1.7.0"
serde = { version = "1.0.154", features = ["derive"] }
serde_json = "1.0.94"

[lib]
name = "mt"
path = "src/lib/main.rs"

[[bin]]
name = "mt"
path = "src/bin/mt.rs"

[[bin]]
name = "mytheme"
path = "src/bin/mytheme.rs"
