[[bin]]
name = "mt"
path = "Source/Binary/mt.rs"

[[bin]]
name = "mytheme"
path = "Source/Binary/mytheme.rs"

[build]
target-dir = "Target"

[dependencies]
clap = { version = "4.5.27", features = ["derive"] }
crossbeam = { version = "0.8.4" }
prql-compiler = "0.12.2"
rayon = { version = "1.10.0" }
rusqlite = { version = "0.33.0", features = ["bundled"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = { version = "1.0.138" }
unbug = { version = "0.4.0" }

[features]
default = []

[lib]
name = "mt"
path = "Source/Library/main.rs"

[package]
default-run = "mt"
description = "Mytheme PRQL Query Compiler"
license-file = "LICENSE"
name = "mytheme"
repository = "https://github.com/MythemeCloud/cargo.git"
version = "0.0.2"
