name: Cargo

concurrency:
    group: cargo-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    security-events: write

on:
    workflow_dispatch:
    release:
        types: [created]
    workflow_call:

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write

        strategy:
            matrix:
                toolchain: ["stable", "nightly"]

        steps:
            - uses: actions/checkout@v3.5.3
            - uses: actions-rs/toolchain@v1.0.7
              with:
                  profile: minimal
                  toolchain: ${{ matrix.toolchain }}

            - uses: actions/cache@v3.3.1
              with:
                  path: |
                      ~/.cargo/bin/
                      ~/.cargo/registry/index/
                      ~/.cargo/registry/cache/
                      ~/.cargo/git/db/
                      target/
                  key: ${{ runner.os }}-cargo-${{ hashFiles('./Cargo.toml') }}

            - uses: actions-rs/cargo@v1.0.3
              with:
                  command: build
                  args: --release --all-features --manifest-path ./Cargo.toml

            - name: Publish ./
              uses: actions-rs/cargo@v1.0.3
              continue-on-error: true
              with:
                  command: publish
                  args: --manifest-path ./Cargo.toml
              env:
                  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
